#!/bin/bash

# =============================================
# ES 8.17.0 集群完整部署流程指引
# =============================================

echo "================================================"
echo "🚀 ES 8.17.0 集群完整部署流程"
echo "================================================"
echo ""
echo "【Step 1】ECS-1 (172.16.0.20) - 系统初始化"
echo "  bash 01-init-ecs1.sh"
echo ""
echo "【Step 2】ECS-1 (172.16.0.20) - 生成 TLS 证书"
echo "  bash 00-generate-certs.sh"
echo ""
echo "【Step 3】ECS-1 (172.16.0.20) - 同步证书到 ECS-2"
echo "  rsync -avz /data/elasticsearch/certs/ \\"
echo "    root@172.16.0.21:/data/elasticsearch/certs/"
echo ""
echo "【Step 4】ECS-2 (172.16.0.21) - 系统初始化"
echo "  bash 01-init-ecs2.sh"
echo ""
echo "【Step 5】ECS-1 (172.16.0.20) - 启动 ES 节点"
echo "  cp -r ecs1 /data/elasticsearch/ecs1"
echo "  cd /data/elasticsearch/ecs1"
echo "  docker-compose up -d"
echo ""
echo "【Step 6】ECS-2 (172.16.0.21) - 启动 ES 节点（先不启动 Kibana）"
echo "  cp -r ecs2 /data/elasticsearch/ecs2"
echo "  cd /data/elasticsearch/ecs2"
echo "  docker-compose up -d es-node3"
echo ""
echo "【Step 7】ECS-1 (172.16.0.20) - 初始化密码"
echo "  bash 02-setup-passwords.sh"
echo ""
echo "【Step 8】ECS-2 (172.16.0.21) - 填入 kibana_system 密码"
echo "  cp /data/elasticsearch/ecs2/.env.example /data/elasticsearch/ecs2/.env"
echo "  vi /data/elasticsearch/ecs2/.env"
echo ""
echo "【Step 9】ECS-2 (172.16.0.21) - 启动 Kibana"
echo "  cd /data/elasticsearch/ecs2"
echo "  docker-compose up -d kibana"
echo ""
echo "【验证】检查集群状态"
echo "  curl -s --cacert /data/elasticsearch/certs/ca/ca.crt \\"
echo "    -u elastic:<your_password> \\"
echo "    https://172.16.0.20:9200/_cluster/health?pretty"
echo ""
echo "  curl -s --cacert /data/elasticsearch/certs/ca/ca.crt \\"
echo "    -u elastic:<your_password> \\"
echo "    https://172.16.0.20:9200/_cat/nodes?v"
echo ""
echo "================================================"
echo "✅ Kibana 访问地址: https://172.16.0.21:5601"
echo "================================================"
